<?php
/**
 *
 *
 * @category Mygento
 * @package Mygento_Simplepay
 * @copyright Copyright © 2015 NKS LLC. (http://www.mygento.ru)
 * @license GPLv2
 */

?>
<strong><?php echo $this->getSimplepayName(); ?></strong>
<?php if ($this->isEmailContext()): ?>
    <?php if ($this->isSendLink()): ?>
        <?php if ($this->isPayable()): ?>
            <?php if (!$this->isPaid()): ?>
                <p><a target="_blank" href="<?php echo $this->getPaylink(); ?>">Оплатить заказ</a></p>
            <?php else: ?>
                <p><?php echo $this->__('Order is paid'); ?></p>
            <?php endif; ?>
        <?php else: ?>
            <p><?php echo $this->__('Order payment is blocked. Please contact store administrator for more questions.') ?></p>
        <?php endif; ?>
    <?php else: ?>
        <?php if (!$this->isPaid()): ?>
            <p><a target="_blank" href="<?php echo $this->getPaylink(); ?>">Оплатить заказ</a></p>
        <?php else: ?>
            <p><?php echo $this->__('Order is paid'); ?></p>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>