<?php
/**
 *
 *
 * @category Mygento
 * @package Mygento_Simplepay
 * @copyright Copyright © 2015 NKS LLC. (http://www.mygento.ru)
 * @license GPLv2
 */

?>
<html>
    <body>
        <?php echo $this->__('You will be redirected to the SimplePay website in a few seconds.'); ?>
        <?php echo $this->getForm()->toHtml(); ?>
        <script type="text/javascript">document.getElementById("simplepay_redirect").submit();</script>
    </body>
</html>
